# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

env:
  PROJECT_NAME: SwiftExtensions

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Run Tests
      run: swift build -v
    - name: Tests
      run: swift test -v 

  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftLint
        uses: sinoru/actions-swiftlint@v6
        env:
          WORKING_DIRECTORY: Source
          

  codecov:
    runs-on: ubuntu-latest
    steps:
      - run: swift test --enable-code-coverage
      - uses: michaelhenry/swifty-code-coverage@v1.0.0
        with:
          build-path: .build
          target: ${{ env.PROJECT_NAME }}Tests.xctest
          is-spm: true
          output: "coverage/lcov.info"
          output-artifact-name: "codeclimate-artifact"
          ignore-filename-regex: '^[\w,\s-]+ViewController\.swift$'

