# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

env:
  PROJECT_NAME: SwiftExtensions

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run Tests
        run: swift test -v --enable-code-coverage
      - name: Code coverage
        uses: maxep/spm-lcov-action@0.3.0
        with:
          output-file: ./coverage/lcov.info

  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftLint
        uses: sinoru/actions-swiftlint@v6
        env:
          WORKING_DIRECTORY: Source

  codecov:
    container:
      image: swift:5.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test -v --enable-code-coverage
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 98
        INCLUDE_TESTS: 'true'

  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Download Swift 5.7.3
        run: wget -q https://download.swift.org/swift-5.7.3-release/ubuntu2204-aarch64/swift-5.7.3-RELEASE/swift-5.7.3-RELEASE-ubuntu22.04-aarch64.tar.gz.sig
      - name: Extract Swift 5.7.3
        run: tar xzf swift-5.7.3-RELEASE-ubuntu22.04-aarch64.tar.gz
      - name: Add Path
        run: echo "::add-path::$GITHUB_WORKSPACE/swift-5.7.3-RELEASE-ubuntu22.04/usr/bin"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

