# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Tests
      run: swift test -v --enable-code-coverage
  codecov:
    container:
      image: swift:5.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Code Coverage
      run: swift test --enable-test-discovery --enable-code-coverage
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 70
        INCLUDE_TESTS: 'true'

