# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

env:
  PROJECT_NAME: SwiftExtensions

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run Tests
        run: swift test -v --enable-code-coverage
      - name: Code coverage
       - uses: mattpolzin/swift-codecov-action@0.7.5
        with:
          MINIMUM_COVERAGE: 98
          INCLUDE_TESTS: 'true'

        #uses: maxep/spm-lcov-action@0.3.0
        #with:
        #  output-file: ./coverage/lcov.info

  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftLint
        uses: sinoru/actions-swiftlint@v6
        env:
          WORKING_DIRECTORY: Source
