# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

env:
  PACKAGE_NAME: SwiftExtensions

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        run: swift build -v
      - name: Swiftlint
        run: swiftlint lint --reporter github-actions-logging #--strict
      - name: Run Tests
        run: swift test -v --enable-code-coverage
      - name: Code coverage
        uses: maxep/spm-lcov-action@0.3.0
        with:
          output-file: ./coverage/reports/coverage_report.lcov
      # - name: Setup Xcode
      #   uses: maxim-lobanov/setup-xcode@v1.4.0
      #   with:
      #     xcode-version: "13.1"

      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/${{ env.PACKAGE_NAME }}Tests.xctest/Contents/MacOS/${{ env.PACKAGE_NAME }}Tests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage_report.lcov
          verbose: true

